name: Generate release notes and create GitHub release

on:
  push:
    tags:
      - 'v[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate release notes
        uses: actions/github-script@v6
        with:
          script: |
            const currentTag = '${{ github.ref }}'
            const previousTag = await github.getPreviousTag()

            const changelog = await github.generateReleaseChangelog({
              fromCommit: previousTag.sha,
              toCommit: currentTag.sha,
            })

            github.outputs.changelog = changelog

      - name: Create GitHub release
        uses: actions/create-release@v3
        with:
          tag_name: '${{ github.ref }}'
          name: '${{ github.ref }}'
          body: '${{ steps.generate_release_notes.outputs.changelog }}'
