name: New Release

###
### Activate when a new tag is pushed
###
on:
    push:
        paths:
            - .github/workflows/release.yml
        tags:
            - '*'
            - '**'

jobs:
    create-release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            # Checkout the repository
            - uses: actions/checkout@v3
            # Get the tag name and set it as TAG_NAME
            - name: Get Tag Name
              id: tag
              run: |
                echo ::set-output name=TAG_NAME::${GITHUB_REF/refs\/tags\//}
                echo "Tag name is $TAG_NAME"
            # Get summary of changes since last release
            - name: Get Summary
              id: summary
              run: |
                echo ::set-output name=SUMMARY::$(git log $(git describe --tags --abbrev=0)..HEAD --oneline)
                echo "Summary is $SUMMARY"
            # Create the release
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.tag.outputs.TAG_NAME }}
                  release_name: Release ${{ steps.tag.outputs.TAG_NAME }}
                  body: |
                    Release: ${{ steps.tag.outputs.TAG_NAME }}
                    Summary: ${{ steps.summary.outputs.SUMMARY }}
                  draft: false
                  prerelease: false
